# Generated by Django 5.1.5 on 2026-01-26 23:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Banco Chile, Cash Wallet', max_length=100)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('credit_card', 'Credit Card'), ('savings', 'Savings Account'), ('investment', 'Investment Account')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('CLP', 'Chilean Peso'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='CLP', max_length=3)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting balance when account was created', max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current balance (calculated from transactions)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-is_active', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
