# Generated by Django 5.1.5 on 2026-01-26 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10)),
                ('color', models.CharField(choices=[('#EF4444', 'Red'), ('#F59E0B', 'Orange'), ('#10B981', 'Green'), ('#3B82F6', 'Blue'), ('#8B5CF6', 'Purple'), ('#EC4899', 'Pink'), ('#6B7280', 'Gray')], default='#3B82F6', help_text='Color for charts and UI', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g., lucide icon name)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category')),
                ('user', models.ForeignKey(blank=True, help_text='Leave blank for default categories', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['transaction_type', 'name'],
                'unique_together': {('name', 'user', 'transaction_type')},
            },
        ),
    ]
